import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  layout("routes/app-layout.tsx", [
    index("routes/home.tsx"),
    route("search", "routes/search.tsx"),
    route("categories", "routes/categories.tsx"),
    route("categories/:slug", "routes/category.tsx"),
    route("rankings/:type", "routes/rankings.tsx"),
    route("books/:bookId", "routes/book-detail.tsx"),
    route("authors/:authorId", "routes/author.tsx"),
    route("login", "routes/login.tsx"),
    route("register", "routes/register.tsx"),
    route("library", "routes/library.tsx"),
    route("history", "routes/history.tsx"),
    route("settings", "routes/settings.tsx"),
    route("creator", "routes/creator.tsx"),
    route("creator/upload", "routes/creator-upload.tsx"),
    route("creator/books/:bookId", "routes/creator-book.tsx"),
    route("creator/books/:bookId/chapters/:chapterId", "routes/creator-editor.tsx"),
    route("admin", "routes/admin.tsx"),
    route("admin/moderation", "routes/admin-moderation.tsx"),
    route("admin/users", "routes/admin-users.tsx"),
    route("admin/operations", "routes/admin-operations.tsx"),
    route("admin/sources", "routes/admin-sources.tsx"),
    route("notifications", "routes/notifications.tsx"),
    route("source/:sourceId/book", "routes/source-book.tsx"),
  ]),
  route("read/:bookId/:chapterId", "routes/reader.tsx"),
  /**
   * 在线源阅读页不进 app-layout：那层有顶栏 + 底部导航 + 内边距，
   * 会把正文可视高度砍掉一大截。与本地阅读器一样独占整屏，
   * 上下栏由页面自己按需显隐。
   */
  route("source/:sourceId/chapter", "routes/source-chapter.tsx"),
  route("api/auth/*", "routes/api.auth.ts"),
  route("api/reader/progress", "routes/api.reader-progress.ts"),
  route("api/reader/preferences", "routes/api.reader-preferences.ts"),
  route("api/reader/bookmarks", "routes/api.reader-bookmarks.ts"),
  route("api/library/shelf", "routes/api.library-shelf.ts"),
  route("api/creator/imports/*", "routes/api.creator-imports.ts"),
  route("api/creator/books/:bookId/*", "routes/api.creator-book.ts"),
  route("api/admin/site-settings", "routes/api.admin-site-settings.ts"),
  route("api/admin/sources/*", "routes/api.admin-sources.ts"),
  route("api/sources/search", "routes/api.sources-search.ts"),
  route("api/sources/reading", "routes/api.source-reading.ts"),
  route("api/creator/chapters/:chapterId/*", "routes/api.creator-chapters.ts"),
  route("api/moderation/tasks/*", "routes/api.moderation.ts"),
  route("api/moderation/books/:bookId", "routes/api.moderation.ts", { id: "api.moderation-books" }),
  route("api/admin/users/*", "routes/api.admin-users.ts"),
  route("api/admin/operations/*", "routes/api.admin-operations.ts"),
  route("api/notifications/*", "routes/api.notifications.ts"),
  route("api/books/:bookId/chapters/:chapterId/content", "routes/api.chapter-content.ts"),
  route("api/books/:bookId/toc", "routes/api.book-toc.ts"),
  route("api/dev/seed", "routes/api.dev-seed.ts"),
] satisfies RouteConfig;
